services:
  accidents_db:
    build:
      context: .
      dockerfile: Dockerfile.accidents_db
    container_name: accidents_db_container
    environment:
      POSTGRES_USER: ${ACCIDENTS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ACCIDENTS_POSTGRES_PASSWORD}
      POSTGRES_DB: ${ACCIDENTS_POSTGRES_DB}
    ports:
      - "${ACCIDENTS_POSTGRES_HOST_PORT}:${ACCIDENTS_POSTGRES_CONT_PORT}"
    volumes:
      - accidents_db_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${ACCIDENTS_POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - data_network
  mlflow_db:
    image: postgres:18.1
    container_name: mlflow_db_container
    environment:
      POSTGRES_USER: ${MLFLOW_POSTGRES_USER}
      POSTGRES_PASSWORD: ${MLFLOW_POSTGRES_PASSWORD}
      POSTGRES_DB: ${MLFLOW_POSTGRES_DB}
    ports:
      - "${MLFLOW_POSTGRES_HOST_PORT}:${MLFLOW_POSTGRES_CONT_PORT}"
    volumes:
      - mlflow_db_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${MLFLOW_POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - mlflow_network
  mlflow_minio:
    image: minio/minio:latest
    container_name: mlflow_minio_container
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "${MINIO_HOST_PORT}:${MINIO_CONT_PORT}"
      - "${MINIO_CONSOLE_HOST_PORT}:${MINIO_CONSOLE_CONT_PORT}"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":${MINIO_CONSOLE_CONT_PORT}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${MINIO_CONT_PORT}/minio/health/live"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - mlflow_network
  create_minio_bucket:
    image: minio/mc:latest
    container_name: create_minio_bucket_container
    depends_on:
      mlflow_minio:
        condition: service_healthy
    entrypoint:
      - /bin/sh
      - -c
      - |
        mc alias set myminio "http://${MINIO_HOST}:${MINIO_CONT_PORT}" \
          "${MINIO_ROOT_USER}" "${MINIO_ROOT_PASSWORD}"
        mc mb --ignore-existing "myminio/${MINIO_BUCKET_NAME}"
    restart: "no"
    
    networks:
      - mlflow_network
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: mlflow_container
    depends_on:
      mlflow_db:
        condition: service_healthy
      mlflow_minio:
        condition: service_healthy
      create_minio_bucket:
        condition: service_completed_successfully
    environment:
      # Backend store configuration
      MLFLOW_BACKEND_STORE_URI: ${MLFLOW_BACKEND_STORE_URI}
      # minIO (S3 compatible) artifact store configuration
      MLFLOW_S3_ENDPOINT_URL: ${MLFLOW_S3_ENDPOINT_URL}
      MLFLOW_ARTIFACTS_DESTINATION: ${MLFLOW_ARTIFACTS_DESTINATION}
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      MLFLOW_S3_IGNORE_TLS: "true"
      # server configuration
      MLFLOW_HOST: ${MLFLOW_HOST}
      MLFLOW_PORT: ${MLFLOW_PORT}
    command:
      - /bin/sh
      - -c
      - |
        mlflow server \
          --backend-store-uri "$${MLFLOW_BACKEND_STORE_URI}" \
          --artifacts-destination "$${MLFLOW_ARTIFACTS_DESTINATION}" \
          --host "$${MLFLOW_HOST}" \
          --port "$${MLFLOW_PORT}"
    ports:
      - "${MLFLOW_PORT}:${MLFLOW_PORT}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${MLFLOW_PORT}/health"]
      interval: 10s
      timeout: 5s
      retries: 30
    networks:
      - mlflow_network
volumes:
  accidents_db_data:
  mlflow_db_data:
  minio_data:
networks:
  mlflow_network:
  data_network:
