services:
  accidents_db:
    build:
      context: .
      dockerfile: Dockerfile.accidents_db
    container_name: accidents_db_container
    environment:
      POSTGRES_USER: ${ACCIDENTS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ACCIDENTS_POSTGRES_PASSWORD}
      POSTGRES_DB: ${ACCIDENTS_POSTGRES_DB}
    ports:
      - "${ACCIDENTS_POSTGRES_PORT}:5432"
    volumes:
      - accidents_db_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${ACCIDENTS_POSTGRES_USER} -h localhost -d ${ACCIDENTS_POSTGRES_DB} -p 5432"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - data_network
  mlflow_db:
    image: postgres:18.1
    container_name: mlflow_db_container
    environment:
      POSTGRES_USER: ${MLFLOW_POSTGRES_USER}
      POSTGRES_PASSWORD: ${MLFLOW_POSTGRES_PASSWORD}
      POSTGRES_DB: ${MLFLOW_POSTGRES_DB}
    ports:
      - "${MLFLOW_POSTGRES_PORT}:5432"
    volumes:
      - mlflow_db_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${MLFLOW_POSTGRES_USER} -h localhost -d ${MLFLOW_POSTGRES_DB} -p 5432"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - mlflow_network
    restart: always
  mlflow_minio:
    build:
      context: .
      dockerfile: Dockerfile.minio
    container_name: mlflow_minio_container
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - mlflow_network
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: mlflow_container
    depends_on:
      mlflow_db:
        condition: service_healthy
      mlflow_minio:
        condition: service_healthy
    environment:
      # Backend store configuration
      MLFLOW_BACKEND_STORE_URI: ${MLFLOW_BACKEND_STORE_URI}
      # MinIO (S3 compatible) artifact store configuration
      MLFLOW_S3_ENDPOINT_URL: ${MLFLOW_S3_ENDPOINT_URL}
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      MLFLOW_PORT: ${MLFLOW_PORT}
    command: ["mlflow", "server", "--backend-store-uri", "${MLFLOW_BACKEND_STORE_URI}", "--artifacts-destination", "${MLFLOW_ARTIFACTS_DESTINATION}", "--host", "0.0.0.0", "--port", "5000"]
    ports:
      - "${MLFLOW_PORT}:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 30
    networks:
      - mlflow_network
volumes:
  accidents_db_data:
  mlflow_db_data:
  minio_data:
networks:
  mlflow_network:
  data_network:
