
services:

# PostgreSQL database for raw and preprocessed data
  postgres:
    image: postgres:16
    container_name: mlops_postgres
    # Variablen kommen aus .env Datei
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # MLflow server container

  mlflow:
    build:
      context: .          # Root des Repositories
      dockerfile: mlflow/Dockerfile
    container_name: mlflow

    environment:
      # AWS/S3 credentials for artifact storage (MinIO)
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
    depends_on:
      - mlflow-db
      - minio  # Ensure backend and artifact storage are ready before starting
    ports:
      - "5000:5000"  # Expose MLflow UI
    volumes:
      - ./tests:/app/tests

  
  # PostgreSQL database for MLflow backend metadata
  mlflow-db:
    image: postgres:16
    container_name: mlflow-db
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow
    ports:
      - "5433:5432"
    volumes:
      - mlflow-db-data:/var/lib/postgresql/data  # Persist database data


  # MinIO container for artifact storage (S3-compatible)
  minio:
    image: quay.io/minio/minio
    container_name: minio
    command: server /data --console-address ":9001"  # Run server and web console
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # Web console
    volumes:
      - minio-data:/data  # Persist artifacts

volumes:
  postgres-data:
  mlflow-db-data:
  minio-data:
