[project]
name = "oct25-bmlops-int-accidents"
version = "0.1.0"
description = "MLOps project to predict the severity of traffic accidents in France based on various features using machine learning techniques."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "joblib>=1.5.2",
    "pandas>=2.3.3",
    "scikit-learn>=1.7.2",
]

[dependency-groups]
dev = [
    "pytest>=9.0.1",
]
